doc/Taskforce2015_Twinkles.md
Hi,
I Just added my name (Nan Li) to the table, and I would like to do some work for "twinkles". If possible, could you please merge this? Thank you.
All the best,
Nan Li
=> Update name list

doc/Design.md
In issue #22 the Extended Chandra Deep Field South was chosen as the best option.
=> Add location of the field to the survey design

code/generatePhosimInput.py
This script is a first go at generating a script
that will create phosim inputs.  The opsim version
is hardcoded, so you'll need to get it from
the sims site.
=> Add a script using catSim to find phosim inputs

twinkles/generatePhosimInput.py, twinkles/sprinkler.py
Random number seeding is now consistent so the same lenses get sprinkled every visit. Also, finally got database timeout right.
This incorporates the random numbers as outlined in #32
=> Consistent Seeding Added

doc/Run1.md
=> Added plans for SN

twinkles/generatePhosimInput.py, twinkles/sprinkler.py, twinkles/twinklesCatalogDefs.py
Catalog information now correctly applied includes coordinates of the lens images, the 'i' band magnitude of the lens galaxy now has correct magnorm scaling and magnification of the source images is handled correctly.
=> Correct application of OM10 catalog information to catsim added. Updated to Kraken.

examples/notebooks/Run1CPUTimes.ipynb
Check it out, @sethdigel ! We have got the cross validation working for the KNN model, but its still not all that great. So, here's what we're going to try and do:
=> Student Empowerment

doc/Cookbook/twinkles_cookbook.md
An --output repo is now required since DM-4692
=> Add --output argument to commands in Cookbook

stylesheets/html.template, stylesheets/pandoc.css, weekly/2016/08/weekly_20160804.html, weekly/index.html
I've mostly got it fully automated.  One final tweak is necessary to get the title set up, I'll try to fix that bit up before next week's weekly :)  Other than that, all we have to do now is download the minutes and run pandocs to produce a nice html file and commit it to the gh-pages branch.
I owe an update to the how-to page for the weekly to specify the new pandoc command-line options.
=> Aug 4 2016 weekly

README.md, doc/LSST_DESC_Notes/0001_twinkles_design/index.rst, doc/LSST_DESC_Notes/0002_twinkles1_inputs/index.rst, doc/LSST_DESC_Notes/0003_twinkles1_phosim_workflow/index.rst, doc/LSST_DESC_Notes/0004_ml_prediction_of_phosim_cpu_time/index.rst, doc/LSST_DESC_Notes/0005_twinkles1_dm_level_2_pipeline/index.rst, doc/LSST_DESC_Notes/0006_twinkles1_workflow_management/index.rst, doc/LSST_DESC_Notes/0007_pserv/index.rst, doc/LSST_DESC_Notes/0008_desc_monitor/index.rst, doc/LSST_DESC_Notes/0009_desc_software_package_template/index.rst, doc/LSST_DESC_Notes/0010_twinkles1_early_photometric_validation/index.rst, doc/LSST_DESC_Notes/0011_twinkles1_early_supernova_light_curves/index.rst
@heather999 I didn't change too much in the end, but hopefully this is a bit more approachable! It now includes a link to the weeklies as our top recommendation for how to find out what's going on., and I removed some extraneous links as well. See what you think!
https://github.com/drphilmarshall/Twinkles/blob/master/README.md
=> Cleaned up README

workflows/DM/processEimage
This addresses #322 
@SimonKrughoff : Is this all we need to turn on to handle cosmic rays?  What about `charImage.repair.doInterpolate`?  Is that relevant for this?
@tony-johnson
=> turn on cosmic ray repair

bin/generatePhosimInput.py, python/desc/twinkles/sprinkler.py
Use final numbers agreed upon in #309
=> Finalize sprinkler parameters for AGN

weekly/2016/09/weekly_20160922.html, weekly/2016/09/weekly_20160929.html, weekly/index.html
@drphilmarshall I finally caught up on the September weekly notes. This PR includes both Sept 22nd and Sept 29th, and can be found here:
https://heather999.github.io/Twinkles/weekly/index.html
=> catch on Sept weeklies

weekly/2016/10/weekly_20161006.html, weekly/2016/10/weekly_20161013.html, weekly/index.html
@drphilmarshall finally here are the first two weeklies for October! You can preview them here in my gh-pages area:
[Oct 6th](https://heather999.github.io/Twinkles/weekly/2016/10/weekly_20161006.html)
[Oct 13th](https://heather999.github.io/Twinkles/weekly/2016/10/weekly_20161013.html)
=> adding Oct 6th and 13th weeklies

bin/generatePhosimInput.py, python/desc/twinkles/twinkles_sky.py
Updated table names to new table name for Twinkles 3. This is essentially a change from 
`TwinkSN` to `TwinkSN_run3`
Fixes #360
=> Issue#360/update table names for sn

workflows/PhoSim/twinkles_I_physics_override.txt
This PR addresses #348, by upgrading the phosim physics over-ride / command file. What else needs to be changed?
=> No contamination, please!

weekly/2016/10/weekly_20161020.html, weekly/index.html
@drphilmarshall , the weekly for last week's meeting is ready.  You can preview the content here:  
https://heather999.github.io/Twinkles/weekly/2016/10/weekly_20161020.html
=> weekly 20161020

python/desc/twinkles/sprinkler.py
To close #379 we want to sort before choosing which om10 system to accept in the sprinkler.
=> Added sorting to sprinkler choices.

bin/view_diffs.py
=> Add a utility to look at diffim repositories

weekly/2017/03/weekly_20170329.html, weekly/2017/04/weekly_20170412.html, weekly/2017/04/weekly_20170419.html, weekly/index.html
Converted all weeklies I felt were ready.. held off on Apr 26th for now.  This includes March 29, April 12th, and April 19th.  The updates can be viewed here:
https://heather999.github.io/Twinkles/weekly/
=> catching up on weeklies thru Apr 19th

python/desc/twinkles/twinkles_io.py
Tried to import twinkles on NERSC and got an error due to the tab indentation in this file.
=> Fix tab error
